### ISSUE TITLE
redesign popup/add new features

### ISSUE THREAD

**Issue by stevenmiller888** [segmentio/daydream#13]
Idea:

1. Home page: start/stop/replay a recording, view a list of previous recordings, delete a recording, export a recording's nightmare script.

2. Recording page: view the steps in the chosen recording in human-readable form (e.g. "Visited http://google.com", "Clicked on the Search button"), delete and reorder steps in the recording.

3. Settings page: type in an optional custom function defining how to generate the query for identifying an element (what `cssPath` is currently doing).

**Comment by lambtron** [comment]
:hamburger:

**Comment by stevenmiller888** [comment]
don't have time to work on this right now
