### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by yoyo1218** [segmentio/daydream#18]
when I follow your step,I meet this problem:
error : Error: Command failed: /bin/sh -c git ls-remote --tags --heads https://github.com/component/emitter
error: The requested URL returned error: 403 while accessing https://github.com/component/emitter/info/refs

how can i resolve it ? Thank you

**Comment by stevenmiller888** [comment]
I'm unable to reproduce that error. Can you provide some information to help me replicate, for example your Node and NPM versions?

**Comment by yoyo1218** [comment]
npm WARN package.json daydream@2.0.0 No license field.
duo@0.8.10 node_modules/duo
├── get-stdin@1.0.0
├── co@3.1.0
├── unyield@0.0.1
├── co-exists@0.0.1
├── stream-log@0.1.0
├── duo-parse@0.1.1
├── bytes@1.0.0
├── duo-css-compat@0.0.4
├── thunkify@2.1.2
├── cp@0.1.1
├── delegates@0.0.3
├── step.js@2.0.5
├── batch@0.5.3
├── extend.js@0.0.1
├── win-fork@1.1.1
├── archy@0.0.2
├── atomic-json@0.0.4 (enqueue@0.0.3)
├── co-parallel@1.0.0 (co-thread@0.0.1)
├── duo-string-to-js@0.1.2 (string-to-js@0.0.1)
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── debug@2.2.0 (ms@0.7.1)
├── json-mask@0.3.5
├── component-clone@0.2.2 (component-type@1.2.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── co-fs@1.2.0 (thunkify@0.0.1, co-from-stream@0.0.0)
├── max-component@1.0.0 (to-function@2.0.6)
├── duo-pack@1.0.10 (combine-source-map@0.3.0)
├── duo-watch@0.1.1 (debug@1.0.4, minimatch@1.0.0, sane@0.5.4)
├── duo-main@0.0.3 (component-type@1.2.0, mocha@1.21.5)
├── duo-package@0.5.1 (thunkify@0.0.1, node-netrc@0.0.1, enstore@0.0.2, semver@2.3.2, gh-resolve@3.1.0, tar-fs@0.4.1, request@2.65.0)
├── language-classifier@0.0.1 (classifier@0.1.0)
├── file-deps@0.0.7 (escape-regexp@0.0.1, mini-tokenizer@0.1.2, detective@3.1.0)
├── duo-test@0.4.1 (incasesensitive@1.0.0, buffer-events@0.0.2, co-exec@1.1.0, open@0.0.5, wd-browser@1.1.0, co-timeout@0.1.0, koa-route@1.1.4, debug@1.0.4, queue-component@1.0.6, which@1.2.0, koa@0.8.2, koa-static@1.5.2, to-pascal-case@0.0.2, bluebird@2.10.2, mocha@1.21.5, localtunnel@1.8.0, wd@0.3.12)
└── gnode@0.1.0 (regenerator@0.6.10)

     building : lib/foreground/popup/index.js
    installed : segmentio-highlight@0.0.3
    installed : segmentio-highlight-javascript@0.0.3
    installed : component-emitter@1.2.0
        error : Error: component-escape-html@v1.0.3: socket hang up
    at Package.error (/home/lushijie/daydream/node_modules/duo/node_modules/duo-package/lib/index.js:506:10)
    at Request.error (/home/lushijie/daydream/node_modules/duo/node_modules/duo-package/lib/index.js:419:22)
    at Request.emit (events.js:107:17)
    at Request.onRequestError (/home/lushijie/daydream/node_modules/duo/node_modules/duo-package/node_modules/request/request.js:867:8)
    at ClientRequest.emit (events.js:107:17)
    at TLSSocket.socketOnEnd (_http_client.js:300:9)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

make: *** [build] 错误 1

1.I have got it on the chrome web store
2.Today when  I   repeated scenes,  I meet this problem .node 0.12.7  npm 2.11.3
3.Maybe it's caused by my network.You must know Chinese network !
4.Your can speak chinese.Amazing!My english is poor!

**Comment by stevenmiller888** [comment]
没有，你的英语说得很好！明白你的意思就好了 。哦，对了，"socket hang up" 可能是网路很慢的问题。能不能再试一下？

**Comment by yoyo1218** [comment]
还是 component-os@0.0.1: socket hang up，估计是公司网络的问题，谢了..

**Comment by stevenmiller888** [comment]
没事！那我就把这个问题关上
