### ISSUE TITLE
Doesn't record at all :/

### ISSUE THREAD

**Issue by krainboltgreene** [segmentio/daydream#19]
I'm clicking the record button, doing things, but all it reports is the basic template.

Let me know what information you need.

**Comment by stevenmiller888** [comment]
Can you provide repro steps? At a minimum, the URL and what you did on that page.

**Comment by michalbe** [comment]
I think that delegation and bubbling of the  events could be an issue in here - when the parent is listening to the events of their children. This is the way most of the frameworks deal with events (like Backbone views etc). This is a blind guess, but I couldn't make it work in any BB app I tried.

I prepared a JsFiddle for this [in here](https://jsfiddle.net/tg2rufdd/1/), as you can see, the output is empty:
![daydream](https://cloud.githubusercontent.com/assets/347657/13382250/274c8026-de70-11e5-90f5-b43b3fbc020f.gif)

**Comment by michalbe** [comment]
Ok, apparently I wasn't right - it's the iframe that makes those problems, not the events delegation.

**Comment by shawninder** [comment]
The icon doesn't even become green in my case, no matter which website I'm on... Don't know if this is the same issue or not

**Comment by michalbe** [comment]
This isn't probably a Daydream issue, it stopped working after last Chrome update. The plugin records everything anyway, even if the icon stays unhighlighted.

**Comment by shawninder** [comment]
Perhaps, but in the end I also get an empty nightmare script

**Comment by jbeyer05** [comment]
Same issue as shawninder here.  Light isn't turning green, and I can't get anything but an empty nightmare script.  Chrome is 49.0.2623.110 on a Mac.

**Comment by antimatter96** [comment]
49.0.2623.112 on Windows. Same problem. Turning off uBlock Origin and Privacy Badger doesnt help either

**Comment by krainboltgreene** [comment]
I think my issue can probably be closed. I don't have any useful
information and I haven't used the plugin in a bit. I'll see if I can
contribute some time to debugging his weekend.

**Comment by antimatter96** [comment]
Trying to find if it works with earlier versions of Chrome. Will update

**Comment by djalmaaraujo** [comment]
Same problem here. Using the latest chrome. I installed daydream for the first time, but it's not working.

**Comment by stevenmiller888** [comment]
Should be fixed now!
