### ISSUE TITLE
Text input broken

### ISSUE THREAD

**Issue by Inconditus** [segmentio/daydream#27]
Daydream isn't capturing text input for me, only clicks. Running Chrome Version 50.0.2661.102 (64-bit) on Mac OS X 10.11, Daydream Version: 2.1.1.

Steps to reproduce:
Go to Github.com
Click Daydream Icon
Click Search box
Type in any text.
Press Enter
Click Daydream Icon again.

Result:

``` js
var Nightmare = require('nightmare');
  yield Nightmare()
    .click('html..is-copy-enabled.emoji-size-boost.is-u2f-enabled body.logged-in.env-production.macintosh.page-dashboard div.header.header-logged-in.true div.container.clearfix div.header-search.js-site-search form.js-site-search-form label.form-control.header-search-wrapper.js-chromeless-input-container.focus input.form-control.header-search-input.js-site-search-focus.')
```

There's no input to be found. Similar results can be achieved through any normal input box as well.

**Comment by martin-eq** [comment]
The documentation says that in order to capture text from a text input you have to press *tab* key after finish your input.

**Comment by stevenmiller888** [comment]
@Inconditus As @martin-eq mentioned, you'll need to make sure to press <kbd>tab</kbd> after typing into the `input` element.
