### ISSUE TITLE
Unable to record more than one action each time

### ISSUE THREAD

**Issue by nelsonic** [segmentio/daydream#36]
Hi! 
Really love the _idea_ of the Daydream Chrome extension!
However each time I try to _use_ it, following the instructions in https://github.com/segmentio/daydream#usage only one single action/step gets recorded ...

When I click on the **black `daydream` icon** it turns green, but as soon as I perform _any_ action on the page e.g. click a link the `daydream` icon turns black again and stops recording. 😢 

I'm running **Chrome Version 56.0.2924.87 (64-bit)** for **Mac** OS Sierra **10.12.3** (16D32)
(both OS and Chrome are the latest versions)

I _must_ be doing _something_ wrong but I cannot figure out what! I've tried deleting the plugin and re-installing it from the Chrome Store but not had luck so far.
Any help diagnosing this would be much appreciated!

**Comment by mkreder** [comment]
I have the exact same problem

**Comment by iteles** [comment]
Me too, same issue 😕

**Comment by stevenmiller888** [comment]
Hey everyone,

I apologize for the slow response.

I just pushed https://github.com/segmentio/daydream/commit/575c8c702bdac83337ca107267f0dae2761ba33b and released a new version to the Web Store. I have tested it and the problem appears resolved. Let me know if this is not the case :)

**Comment by iteles** [comment]
Thanks @stevenmiller888 , I'll be trying it over the weekend 🎉

**Comment by nelsonic** [comment]
@stevenmiller888 thanks for replying (_we know you're busy, so we really appreciate your time/help_!)
just re-installed the plugin `v2.1.2` and while it _appears_ to record more than one action, it skips steps.

For example I am simulating the "DuckDuckGo" instructions in https://github.com/segmentio/nightmare#examples

+ Start Daydream recording
+ Visit: https://duckduckgo.com
+ Type: "**github nightmare**" into the search box
+ Click "search" button (_icon_)
+ See search results.

But the Plugin does not pick up the **typing** part. this is what it captured:
![daydream-not-recording-type-action](https://cloud.githubusercontent.com/assets/194400/23252331/602041b8-f9a8-11e6-9010-4cced7a38208.png)

Using the latest version of the plugin:
![chrome-daydream-plugin-enabled](https://cloud.githubusercontent.com/assets/194400/23252394/96f4ab34-f9a8-11e6-8ddd-5fec4d7fdf4a.png)

The only other Chrome Plugin I have enabled is "Cast" (_which I think is enabled by default now..._)

**Comment by stevenmiller888** [comment]
@nelsonic Ah, got it. Did you see this [note](https://github.com/segmentio/daydream#notes)? You need to make sure to press <kbd>tab</kbd> after you finish typing in the `input` element.

**Comment by nelsonic** [comment]
![image](https://cloud.githubusercontent.com/assets/194400/23275148/477348fe-f9fd-11e6-928c-588efbb62ac0.png)

@stevenmiller888 thanks for reminding me to use the `tab` key after text input. 
I hadn't realised it was important. guessing it signals the "_done typing_" so the final input is captured not all keystrokes. 👍

**Comment by nelsonic** [comment]
Thanks @stevenmiller888 ❤️
