### ISSUE TITLE
output code

### ISSUE THREAD

**Issue by shtefcs** [segmentio/daydream#7]
Hi there,

Your extension is awesome, something i was looking for.  I was playing with https://github.com/ebrehault/resurrectio which is for Casperjs.

Anyway, check the screenshot below how styled code i got. Tell me is this normal, or should be nice like on ur screenshot.

![screenshot](http://content.screencast.com/users/shtefcs/folders/Jing/media/77e6b657-cbc1-4e32-9961-f424c94cb06b/2015-02-26_2103.png)

**Comment by stevenmiller888** [comment]
@shtefcs Weird, I'm not able to replicate on my end. Does it happen every time or just with certain flows? Can you send a flow that I can test?

**Comment by shtefcs** [comment]
i tested two sites. Code from screenshot is from reddit login and checking comments

**Comment by stevenmiller888** [comment]
How about a flow without logging in? I don't feel like making a Reddit account haha

**Comment by stevenmiller888** [comment]
@shtefcs Are you running Windows?

**Comment by shtefcs** [comment]
Sorry for late response. Here is code without login

 `var Nightmare = require('nightmare');  new Nightmare()    .click('div#siteTable.sitetable.linklisting div..thing.id-t3_2x8rqz.even.link. div.entry.unvoted ul.flat-list.buttons li.first a.comments.may-blank')    .click('form#form-t1_coxzo3d1rc.usertext div.usertext-body.may-blank-within.md-container div.md p a')    .click('ul#sr-bar.flat-list.sr-bar.hover li a.choice')    .run();`

Yes, I am on W7.

**Comment by stevenmiller888** [comment]
Ah okay, that's because it's using `\n` for line breaks. Just gotta add a little OS detection and use `\r\n` for Windows. I'll message you here once I've pushed up a fix :)

**Comment by stevenmiller888** [comment]
Just pushed. Can you pull down the latest of this repo and test it? I don't have Windows haha

**Comment by shtefcs** [comment]
Hi, I would like to try it, but i dont know how to use it as repo. Can u update in Chrome store ur code ?

**Comment by shtefcs** [comment]
Sorry for late response. Here is code without login

 `var Nightmare = require('nightmare');  new Nightmare()    .click('div#siteTable.sitetable.linklisting div..thing.id-t3_2x8rqz.even.link. div.entry.unvoted ul.flat-list.buttons li.first a.comments.may-blank')    .click('form#form-t1_coxzo3d1rc.usertext div.usertext-body.may-blank-within.md-container div.md p a')    .click('ul#sr-bar.flat-list.sr-bar.hover li a.choice')    .run();`

Yes, I am on W7.

**Comment by stevenmiller888** [comment]
@shtefcs Unfortunately, no. Best to test this out before deploying to the store. You can run it locally by following the steps [here](https://github.com/segmentio/daydream#developing). Let me know if you need help with that :)

**Comment by shtefcs** [comment]
cant do that on windows, cause its not for development ... Anyway, i did what u said and tried on my Dev box Ubuntu and its working fine ![](http://content.screencast.com/users/shtefcs/folders/Jing/media/6fc894b4-60bc-4289-bb12-812b6c9f1065/2015-02-28_0040.png)

**Comment by MatthewMueller** [comment]
Actually same thing seems to be happening on Mac. Just installed it

**Comment by stevenmiller888** [comment]
@MatthewMueller Just pushed some changes that *should* solve this. It'll take about an hour for the Chrome Web Store to publish the new version.

**Comment by stevenmiller888** [comment]
Closing. Lmk if you're still seeing it happen.
